### ISSUE TITLE
Use Input Arguments in GitHub-Action Step

### ISSUE THREAD

**Issue by ric-evans** [WIPACrepo/wipac-dev-py-setup-action#16]
We have a good deal of constants used for generating the `setup.cfg` file. Let's make these configurable using input arguments in the GitHub Action step.

For example, the current values would be defined like this:

```
       py-setup:
        runs-on: ubuntu-latest
        steps:
          - name: checkout
            uses: actions/checkout@v3
            with:
              token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          - uses: WIPACrepo/wipac-dev-py-setup-action@v1.#
            with:
              author: WIPAC Developers
              author_email: developers@icecube.wisc.edu
              default_base_keywords: WIPAC IceCube
              default_directory_exclude: test tests doc docs resource resources
              license: MIT
```

We'll need to decide which of these should be mandatory or optional.
